services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:amehmathias049@db:5432/tasks
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: amehmathias049
      POSTGRES_DB: tasks
    volumes:
      - taskdata:/var/lib/postgresql

volumes:
  taskdata:
